env:
  browser: true
  es2021: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - prettier
overrides: []
parserOptions:
  ecmaFeatures:
   tsx:
    true
  project:
    - tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  "@typescript-eslint/strict-boolean-expressions":
    "off"
  "@typescript-eslint/explicit-function-return-type":
   "off"
  "indent":
    ["error", 4]
  '@typescript-eslint/indent': 
    ['error', 4]
  '@typescript-eslint/no-explicit-any':
   "off"
  "semi": "off"
  "@typescript-eslint/semi": "off"
  "react/react-in-jsx-scope": "off"
settings:
  react:
   pragma: react
   version: detect
  "import/resolver":
   typescript: {}
